@startuml

header Демо проект
title Схема связи

hide circle

entity users {
  * **id**  :  int
  __
  **login**  :  varchar
  **password**  :  varchar
}

entity chats {
  * **id**  :  int
  __
  * **admin**  :  int
  **title** : varchar

}

entity chats_message {
  * **id**  :  int
  __
  * **chat**  :  int
  * **user**  :  int
  **text** : str
}

entity chats_member {
  * **id**  :  int
  --
  * **chat**  :  int
  * **user**  :  int
  **former_members**  :  bool
  **black_list**  :  bool
}


users --o{ chats
users --o{ chats_member
users --o{ chats_message
chats --o{ chats_member
chats --o{ chats_message
@enduml
