@startuml

header Демо проект чата
title Диаграмма прецедентов

left to right direction

rectangle "Авторизация" {
  usecase "Регистрация" as registration
  usecase "Аутентификация" as authentication
}


rectangle "Чат" {
  usecase "Обновление информации о чате" as information_update
  usecase "Удаление чата" as delete
  usecase "Создать чат" as create
  usecase "Получить информацию о чате" as get_info
  usecase "Обновить информацию о чате" as update_info
  usecase "Добавить пользователя в чат" as add_user
  usecase "Выгнать пользователя из чата" as kick_user
  usecase "Выйти из чата" as go_out
  usecase "Войти в чат" as come_in
  usecase "Посмотреть участников чата" as get_users

}

rectangle "Сообщение" {
  usecase "Отправка сообщений в чат" as send_message
  usecase "Получение списка сообщений чата" as get_messages
}

actor "Анонимный ользователь" as user
user -- registration
user -- authentication

actor "Пользователь" as auth_user
auth_user -- create

actor "Создатель чата" as creator_chat_user
creator_chat_user -- information_update
creator_chat_user -- add_user
creator_chat_user -- kick_user

creator_chat_user -- update_info
creator_chat_user -- delete



actor "Пользователь чата" as chat_user
chat_user -- get_users
chat_user -- go_out
chat_user -- come_in
chat_user -l-- send_message
chat_user -- get_info
chat_user -l-- get_messages


@enduml
